"""db columl type change

Revision ID: 6b434d9efae8
Revises: 84e64e060e69
Create Date: 2025-07-09 16:59:56.348252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b434d9efae8'
down_revision = '84e64e060e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ems_order',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ems_order')
    # ### end Alembic commands ###
