"""empty message

Revision ID: f413fa23a943
Revises: 6b434d9efae8
Create Date: 2025-07-12 22:19:24.741937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f413fa23a943'
down_revision = '6b434d9efae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esm_order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ems_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('esm_orderitem',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('prices_at_order', sa.Float(), nullable=False),
    sa.Column('order_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['esm_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['ems_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ems_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ems_order',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ems_order_pkey'))
    )
    op.drop_table('esm_orderitem')
    op.drop_table('esm_order')
    # ### end Alembic commands ###
